version: "3"
services:
    vpp_client:
       build: .
       stdin_open: true
       tty: true
       working_dir: /workspace
       container_name: vpp_client
       hostname: client
       volumes:
            - /tmp/memif:/memif
            - ..:/workspace
       entrypoint: [/bin/bash, -c]
       command: 
        - |
          mkdir -p /var/log/vpp
          tee -a /etc/vpp/startup.conf <<EOF
          plugins {
               plugin default { disable }
               plugin acl_plugin.so { enable }
               plugin ping_plugin.so { enable }
               plugin memif_plugin.so { enable }
               plugin hicn_plugin.so { enable }
          }
          unix { exec | startup-config  /etc/vpp/client-up.txt }
          EOF
          tee -a /etc/vpp/client-up.txt <<EOF
          create memif socket id 1 filename /memif/memif1.sock
          create interface memif id 0 socket-id 1 slave
          set int state memif1/0 up
          set int ip addr memif1/0 192.168.1.1/24
          set int ip addr memif1/0 2001::1/64
          ip route add b002::1/64 via 2001::2 memif1/0
          hicn enable b002::1/64
          EOF
          sleep 5
          vpp -c /etc/vpp/startup.conf &
          sleep 20
          hiperf -C b002::1
          /bin/bash
    vpp_server:
        build: .
        stdin_open: true
        tty: true
        working_dir: /workspace
        container_name: vpp_server
        hostname: server
        volumes:
             - /tmp/memif:/memif
             - ..:/workspace
        entrypoint: [/bin/bash, -c]
        command: 
        - |
          mkdir -p /var/log/vpp
          tee -a /etc/vpp/startup.conf <<EOF
          plugins {
               plugin default { disable }
               plugin acl_plugin.so { enable }
               plugin ping_plugin.so { enable }
               plugin memif_plugin.so { enable }
               plugin hicn_plugin.so { enable }
          }
          unix { exec | startup-config  /etc/vpp/server-up.txt }
          EOF
          tee -a /etc/vpp/server-up.txt <<EOF
          create memif socket id 1 filename /memif/memif1.sock
          create interface memif id 0 socket-id 1 master
          set int state memif1/0 up
          set int ip addr memif1/0 192.168.1.2/24
          set int ip addr memif1/0 2001::2/64
          EOF
          sleep 2
          vpp -c /etc/vpp/startup.conf &
          sleep 10
          hiperf -S b002::/64
          /bin/bash
