version: "3"
services:
    vpp_server:
       build: .
       stdin_open: true
       tty: true
       working_dir: /workspace
       container_name: vpp_client
       hostname: client
       volumes:
            - /tmp/memif:/memif
            - ..:/workspace
       entrypoint: [/bin/bash, -c]
       command: 
        - |
          tee -a /etc/vpp/startup.conf <<EOF
          plugins {
               plugin default { enable }
               plugin hicn_plugin.so { enable }
          }
          unix { exec | startup-config  /etc/vpp/client-up.txt }
          EOF
          tee -a /etc/vpp/client-up.txt <<EOF
          create memif socket id 1 filename /memif/memif1.sock
          create interface memif id 0 socket-id 1 slave
          set int state memif1/0 up
          set int ip addr memif1/0 192.168.1.1/24
          set int ip addr memif1/0 2001::1/64
          set interface state memif1/0
          ip route add b002::1/64 via 2001::2 memif1/0
          hicn enable b002::1/64
          EOF
          /bin/bash
    vpp_client:
        build: .
        stdin_open: true
        tty: true
        working_dir: /workspace
        container_name: vpp_server
        hostname: server
        volumes:
             - /tmp/memif:/memif
             - ..:/workspace
        entrypoint: [/bin/bash, -c]
        command: 
        - |
          tee -a /etc/vpp/startup.conf <<EOF
          plugins {
               plugin default { enable }
               plugin hicn_plugin.so { enable }
          }
          unix { exec | startup-config  /etc/vpp/server-up.txt }
          EOF
          tee -a /etc/vpp/server-up.txt <<EOF
          create memif socket id 1 filename /memif/memif1.sock
          create interface memif id 0 socket-id 1 master
          set int state memif1/0 up
          set int ip addr memif1/0 192.168.1.2/24
          set interface ip address memif1/0 2001::2/64
          set interface state memif1/0 up
          EOF
          /bin/bash
    dev:
        build: .
        container_name: vpp_dev
        hostname: dev
        stdin_open: true
        tty: true
        working_dir: /workspace
        volumes:
             - ..:/workspace
        entrypoint: [/bin/bash]